# Generated by Django 4.0.8 on 2022-11-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_profile_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="membership",
            field=models.CharField(
                choices=[("PREMIUM", "PREMIUM"), ("FREE", "FREE")],
                default="FREE",
                max_length=8,
            ),
        ),
    ]
