# Generated by Django 4.0.8 on 2022-11-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="completed",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
